import numpy as np
a = np.array([1, 2, 3, 4, 5])
print("array:\n",a)
median_a = np.median(a) 
print("median:",median_a)
mean_a = np.mean(a)
print("mean:",mean_a)
minimum_a = np.min(a)
print("minimum:",minimum_a)
maximum_a = np.max(a) 
print("maximum:",maximum_a)
imin_a = np.argmin(a)
print("imin:",imin_a)
imax_a = np.argmax(a) 
print("imax:",imax_a)
standard_deviation_a = np.std(a)
print("standard deviation",standard_deviation_a)
variance_a = np.var(a)  
print("variance:",variance_a)
prod_a=np.prod(a)
print("product:",prod_a)
cumsum_a=np.cumsum(a)
print("cummulative sum:",cumsum_a)
sum_a = np.sum(a) 
print("sum:",sum_a)