import pandas as pd
a=pd.Series([10,20,30,40,50])
b=pd.Series([40,50,60,70,80])
print("Series A:")
print(a)
print("\nSeries B:")
print(b)
non_com=a[~a.isin(a)].tolist()+b[~b.isin(a)].tolist()
print("\nItems not common to both:\n")
print(non_com)
print("\nAverage of series a:\n",a.mean())
print("\nlargest element in series a:\n",a.max())
print("\nsmallest element in series a:\n",a.min())
print("\nMedian of series b:\n",b.median())